FROM public.ecr.aws/lambda/python:3.11

# Instala Git
RUN yum install -y git

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

RUN pip install --no-cache-dir torch

# Install the specified packages
RUN pip install --no-cache-dir -r requirements.txt


# Copy function code. This copies EVERYTHING inside the app folder to the lambda root.
COPY ./app ${LAMBDA_TASK_ROOT}

# Preload the ColPali model and processor weights during build
RUN python -c " \
from colpali import ColPali, ColPaliProcessor; \
ColPali.from_pretrained('vidore/colpali-v1.3', torch_dtype=torch.bfloat16, device_map='cpu').save_pretrained('/opt/colpali_model'); \
ColPaliProcessor.from_pretrained('vidore/colpaligemma-3b-pt-448-base').save_pretrained('/opt/colpali_processor')"

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
# Since we copied 
CMD ["main.handler"]
