version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking branch..."
      - BRANCH_NAME=$(echo $CODEBUILD_SOURCE_VERSION | sed 's|^refs/heads/||')
      - echo "Current branch: $BRANCH_NAME"

      # Only deploy if the branch is "deploy/manuales"
      - |
        if [ "$BRANCH_NAME" != "deploy/manuales" ]; then 
          echo "Skipping deployment"; 
          exit 0; 
        fi
      
      - echo "Setting up the environment..."
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      
      # Define variables in one command (YAML requires commands to be strings)
      - |
        export S3_BUCKET_NAME="talma-artifacts"
        export S3_DOWNLOAD_PATH="lambda_source_files/app"
        export LOCAL_DOWNLOAD_PATH="./lambda_source/manuales/app"

      # Create the target directory
      - mkdir -p "$LOCAL_DOWNLOAD_PATH"

      # Download required directories from S3
      - aws s3 cp "s3://$S3_BUCKET_NAME/$S3_DOWNLOAD_PATH/datasets_local" "$LOCAL_DOWNLOAD_PATH/datasets_local" --recursive
      - aws s3 cp "s3://$S3_BUCKET_NAME/$S3_DOWNLOAD_PATH/local_model" "$LOCAL_DOWNLOAD_PATH/local_model" --recursive
      - aws s3 cp "s3://$S3_BUCKET_NAME/$S3_DOWNLOAD_PATH/local_processor" "$LOCAL_DOWNLOAD_PATH/local_processor" --recursive

  build:
    commands:
      - echo "Debugging deploy.sh execution..."
      - cat deploy.sh
      - ls -l deploy.sh
      - file deploy.sh
      - chmod +x deploy.sh
      - ./deploy.sh -dev

  post_build:
    commands:
      - echo "Deployment completed successfully."
