env                     = "dev"
app_prefix              = "talmaai"
ecr_repo_name           = "docker-repo"
dynamodb_table_name     = "incidentes"
dynamodb_billing_mode   = "PAY_PER_REQUEST"
dynamodb_partition_key  = "id_generation"
dynamodb_partition_key_type = "S"
artifacts_bucket_name   = "artifacts"